version: "2.1"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:0.6.20
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      - /home/matt/Documents/calibre/data:/config
      - /home/matt/Documents/calibre/library:/books
    ports:
      - 8083:8083
    restart: unless-stopped
